name: nepa
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==2.8.0
      - torchvision
      - transformers==4.56.2
      - diffusers
      - accelerate>=0.12.0
      - datasets==3.6.0
      - evaluate
      - scikit-learn
      - timm
